# Generated by Django 5.0.3 on 2025-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.URLField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('director', models.CharField(max_length=255)),
            ],
        ),
    ]
